---
- hosts: all
  vars:
    package_names:
      - vim 
      - oracle-cloud-agent
  tasks:
    - name: "Check if listed package is installed or not on Debian Linux family"
      package:
        name: "{{ item }}"
        state: present
      check_mode: true
      loop: "{{ package_names }}"
      register: package_check

    - name: "Print execution results"
      debug:
        msg: "Package is installed"
      when: package_check is succeeded
